import json
import re
from pathlib import Path

import pytest

from scripts import bump_version
from scripts import validate_desktop_candidate as validator

REPO_ROOT = Path(__file__).resolve().parents[1]


def _rewrite_with_newline(root: Path, newline: str) -> None:
    for relative in bump_version.VERSION_FILES:
        path = root / relative
        data = path.read_bytes().replace(b"\r\n", b"\n")
        path.write_bytes(data.replace(b"\n", newline.encode("ascii")))


def _write(path: Path, text: str) -> None:
    """Write LF-terminated text regardless of the host platform.

    Path.write_text translates "\\n" to os.linesep on Windows, which would make
    these fixtures CRLF there and hide real line-ending regressions.
    """
    path.write_bytes(text.encode("utf-8"))


def _repo_fixture(root: Path, version: str = "0.4.0") -> None:
    """Materialize only the files bump_version rewrites."""
    (root / "gui/src-tauri").mkdir(parents=True, exist_ok=True)
    _write(root / "VERSION", f"{version}\n")
    _write(
        root / "codex-instruct.py",
        f'#!/usr/bin/env python3\n__version__ = "{version}"\nVERSION = __version__\n',
    )
    _write(
        root / "gui/package.json",
        json.dumps(
            {"name": "codex-keysmith-gui", "private": True, "version": version},
            indent=2,
        )
        + "\n",
    )
    _write(
        root / "gui/package-lock.json",
        json.dumps(
            {
                "name": "codex-keysmith-gui",
                "version": version,
                "lockfileVersion": 3,
                "packages": {
                    "": {"name": "codex-keysmith-gui", "version": version},
                    "node_modules/left-pad": {"version": "1.3.0"},
                },
            },
            indent=2,
        )
        + "\n",
    )
    _write(
        root / "gui/src-tauri/Cargo.toml",
        "[package]\n"
        'name = "codex-keysmith-gui"\n'
        f'version = "{version}"\n'
        'edition = "2021"\n'
        "\n"
        "[dependencies]\n"
        'serde = "1"\n',
    )
    _write(
        root / "gui/src-tauri/Cargo.lock",
        "# This file is automatically @generated by Cargo.\n"
        "version = 4\n"
        "\n"
        "[[package]]\n"
        'name = "codex-keysmith-gui"\n'
        f'version = "{version}"\n'
        "dependencies = [\n"
        ' "serde",\n'
        "]\n"
        "\n"
        "[[package]]\n"
        'name = "winapi"\n'
        'version = "0.3.9"\n'
        'source = "registry+https://github.com/rust-lang/crates.io-index"\n',
    )


def test_repository_source_versions_are_synchronized():
    """The real tree must never ship a partial version bump (regression for PR #68)."""
    versions = bump_version.read_versions(REPO_ROOT)

    assert set(versions) == set(bump_version.VERSION_FILES)
    assert len(set(versions.values())) == 1, versions
    assert versions["VERSION"] == (REPO_ROOT / "VERSION").read_text(encoding="ascii").strip()


def test_check_versions_agrees_with_desktop_candidate_validation():
    """The fast gate and the slow desktop gate must never reach different verdicts."""
    assert bump_version.check_versions(REPO_ROOT) == validator.validate_config(REPO_ROOT)[
        "desktop_version"
    ]


def test_tracked_files_cover_every_version_validate_config_checks():
    """A new version-bearing file must not silently escape the fast gate."""
    checked = set(bump_version.VERSION_FILES) | {"gui/src-tauri/tauri.conf.json"}
    source = (REPO_ROOT / "scripts/validate_desktop_candidate.py").read_text(
        encoding="utf-8"
    )
    declared = set(re.findall(r'^\s+"([^"]+)": \w+_version,$', source, re.MULTILINE))

    assert declared - {"VERSION", "codex-instruct.py"} <= checked
    assert checked >= declared


def test_tauri_config_is_not_rewritten_because_it_inherits_the_version():
    assert "gui/src-tauri/tauri.conf.json" not in bump_version.VERSION_FILES

    tauri = json.loads(
        (REPO_ROOT / "gui/src-tauri/tauri.conf.json").read_text(encoding="utf-8")
    )

    assert tauri["version"] == "../package.json"


def test_bump_rewrites_every_tracked_file(tmp_path):
    _repo_fixture(tmp_path)

    result = bump_version.bump(tmp_path, "0.5.0")

    assert result["previous_version"] == "0.4.0"
    assert result["version"] == "0.5.0"
    assert result["changed"] == list(bump_version.VERSION_FILES)
    assert bump_version.read_versions(tmp_path) == {
        relative: "0.5.0" for relative in bump_version.VERSION_FILES
    }


def test_bump_is_byte_reversible(tmp_path):
    _repo_fixture(tmp_path)
    before = {
        relative: (tmp_path / relative).read_bytes()
        for relative in bump_version.VERSION_FILES
    }

    bump_version.bump(tmp_path, "0.5.0")
    bump_version.bump(tmp_path, "0.4.0")

    assert {
        relative: (tmp_path / relative).read_bytes()
        for relative in bump_version.VERSION_FILES
    } == before


def test_bump_preserves_unrelated_lock_entries(tmp_path):
    _repo_fixture(tmp_path)

    bump_version.bump(tmp_path, "0.5.0")

    cargo_lock = (tmp_path / "gui/src-tauri/Cargo.lock").read_text(encoding="utf-8")
    package_lock = json.loads(
        (tmp_path / "gui/package-lock.json").read_text(encoding="utf-8")
    )

    assert 'name = "winapi"\nversion = "0.3.9"' in cargo_lock
    assert package_lock["packages"]["node_modules/left-pad"]["version"] == "1.3.0"
    assert package_lock["lockfileVersion"] == 3


@pytest.mark.parametrize("newline", ["\n", "\r\n"])
def test_bump_preserves_existing_line_endings(tmp_path, newline):
    """A bump must not silently convert a whole file's line endings."""
    _repo_fixture(tmp_path)
    _rewrite_with_newline(tmp_path, newline)
    before = {
        relative: (tmp_path / relative).read_bytes()
        for relative in bump_version.VERSION_FILES
    }

    bump_version.bump(tmp_path, "0.5.0")

    encoded = newline.encode("ascii")
    for relative in bump_version.VERSION_FILES:
        data = (tmp_path / relative).read_bytes()
        assert b"0.5.0" in data
        assert data.count(encoded) == before[relative].count(encoded), relative
        if newline == "\n":
            assert b"\r\n" not in data, relative

    bump_version.bump(tmp_path, "0.4.0")

    assert {
        relative: (tmp_path / relative).read_bytes()
        for relative in bump_version.VERSION_FILES
    } == before


def test_read_versions_handles_crlf_sources(tmp_path):
    _repo_fixture(tmp_path)
    _rewrite_with_newline(tmp_path, "\r\n")

    assert bump_version.check_versions(tmp_path) == "0.4.0"


def test_bump_rejects_a_tree_that_already_disagrees(tmp_path):
    """A partial bump must not be silently adopted as the new baseline."""
    _repo_fixture(tmp_path)
    lock = tmp_path / "gui/src-tauri/Cargo.lock"
    _write(
        lock,
        lock.read_text(encoding="utf-8").replace(
            'name = "codex-keysmith-gui"\nversion = "0.4.0"',
            'name = "codex-keysmith-gui"\nversion = "0.3.9"',
        ),
    )

    with pytest.raises(bump_version.BumpError, match="source versions disagree"):
        bump_version.bump(tmp_path, "0.5.0")

    assert 'version = "0.3.9"' in lock.read_text(encoding="utf-8")


def test_bump_rejects_a_non_semver_target(tmp_path):
    _repo_fixture(tmp_path)

    with pytest.raises(bump_version.BumpError, match="MAJOR.MINOR.PATCH"):
        bump_version.bump(tmp_path, "0.5")


def test_bump_rejects_an_unchanged_version(tmp_path):
    _repo_fixture(tmp_path)

    with pytest.raises(bump_version.BumpError, match="already 0.4.0"):
        bump_version.bump(tmp_path, "0.4.0")


def test_dry_run_reports_the_plan_without_writing(tmp_path):
    _repo_fixture(tmp_path)
    before = {
        relative: (tmp_path / relative).read_bytes()
        for relative in bump_version.VERSION_FILES
    }

    result = bump_version.bump(tmp_path, "0.5.0", dry_run=True)

    assert result["dry_run"] is True
    assert result["version"] == "0.5.0"
    assert {
        relative: (tmp_path / relative).read_bytes()
        for relative in bump_version.VERSION_FILES
    } == before


def test_failed_bump_restores_every_file(tmp_path, monkeypatch):
    _repo_fixture(tmp_path)
    before = {
        relative: (tmp_path / relative).read_bytes()
        for relative in bump_version.VERSION_FILES
    }

    def explode(path, new_version):
        raise bump_version.BumpError("simulated failure")

    monkeypatch.setitem(bump_version.BUMPERS, "gui/src-tauri/Cargo.lock", explode)

    with pytest.raises(bump_version.BumpError, match="simulated failure"):
        bump_version.bump(tmp_path, "0.5.0")

    assert {
        relative: (tmp_path / relative).read_bytes()
        for relative in bump_version.VERSION_FILES
    } == before


def test_failed_restore_is_reported_instead_of_leaving_a_silent_mixed_tree(
    tmp_path, monkeypatch, capsys
):
    _repo_fixture(tmp_path)
    real_write_bytes = Path.write_bytes
    rolling_back = {"active": False}

    def failing_restore(self, data):
        # Only sabotage the rollback, so the original failure must survive.
        if rolling_back["active"] and self.name == "VERSION":
            raise OSError("simulated restore failure")
        return real_write_bytes(self, data)

    def explode_and_start_rollback(path, new_version):
        rolling_back["active"] = True
        raise bump_version.BumpError("simulated failure")

    monkeypatch.setitem(
        bump_version.BUMPERS, "gui/src-tauri/Cargo.lock", explode_and_start_rollback
    )
    monkeypatch.setattr(Path, "write_bytes", failing_restore)

    with pytest.raises(bump_version.BumpError, match="simulated failure"):
        bump_version.bump(tmp_path, "0.5.0")

    assert "failed to restore VERSION" in capsys.readouterr().err


def test_post_bump_validation_failure_rolls_back(tmp_path, monkeypatch):
    _repo_fixture(tmp_path)
    before = {
        relative: (tmp_path / relative).read_bytes()
        for relative in bump_version.VERSION_FILES
    }

    def stale_write(path, new_version):
        return "0.4.0"

    monkeypatch.setitem(bump_version.BUMPERS, "gui/package.json", stale_write)

    with pytest.raises(bump_version.BumpError, match="source versions disagree"):
        bump_version.bump(tmp_path, "0.5.0")

    assert {
        relative: (tmp_path / relative).read_bytes()
        for relative in bump_version.VERSION_FILES
    } == before


def test_bump_rejects_a_duplicate_cargo_lock_entry(tmp_path):
    _repo_fixture(tmp_path)
    lock = tmp_path / "gui/src-tauri/Cargo.lock"
    _write(
        lock,
        lock.read_text(encoding="utf-8")
        + "\n[[package]]\n"
        'name = "codex-keysmith-gui"\n'
        'version = "0.4.0"\n',
    )

    with pytest.raises(bump_version.BumpError, match="exactly one"):
        bump_version.bump(tmp_path, "0.5.0")


def test_cli_check_and_set_round_trip(tmp_path, capsys):
    _repo_fixture(tmp_path)

    assert bump_version.main(["--root", str(tmp_path), "check"]) == 0
    assert json.loads(capsys.readouterr().out) == {"version": "0.4.0"}

    assert bump_version.main(["--root", str(tmp_path), "set", "0.5.0"]) == 0
    assert json.loads(capsys.readouterr().out)["version"] == "0.5.0"

    assert bump_version.main(["--root", str(tmp_path), "check"]) == 0
    assert json.loads(capsys.readouterr().out) == {"version": "0.5.0"}


def test_cli_reports_failure_without_a_traceback(tmp_path, capsys):
    _repo_fixture(tmp_path)

    assert bump_version.main(["--root", str(tmp_path), "set", "nope"]) == 1

    captured = capsys.readouterr()
    assert captured.out == ""
    assert "version bump failed" in captured.err
